[package]
name = "kcctl"
version = "0.1.0"
authors = ["cwlo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.33.0", features = ["yaml"]}
dirs = "3.0.1"
config = "0.10.1"

