[package]
name = "kcctl"
version = "0.1.0"
authors = ["Ben Sayers <bsayers2302@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.33.0", features = ["yaml"]}
xdg = "2.2.0"
